# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  CLIP-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]
        pytorch-version: [2.5.0, 2.8.0]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv pip install --system -e . torch==${{ matrix.pytorch-version }} torchvision pytest --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Run tests
        run: uv run pytest
