# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CLIP-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        pytorch-version: [2.5.0, 2.6.0]

    steps:
      - uses: conda-incubator/setup-miniconda@v4
      - run: conda install -n test python=${{ matrix.python-version }} pytorch=${{ matrix.pytorch-version }} torchvision cpuonly -c pytorch
      - uses: actions/checkout@v4
      - run: echo "$CONDA/envs/test/bin" >> $GITHUB_PATH
      - run: pip install pytest
      - run: pip install .
      - run: pytest
